FROM centos:8
MAINTAINER kusari-k

#repl=replication
ARG SSL_DOMAIN 
ARG replSSL_DOMAIN
ARG USER_DOMAIN
ARG password="cyrus_password"
ARG replpassword="cyrus_rep_password"
ENV Cpass $password

RUN sed -i -e "\$a fastestmirror=true" /etc/dnf/dnf.conf
RUN dnf update -y && \
	dnf install -y rsyslog cyrus-imapd cyrus-sasl cyrus-sasl-plain && \
	dnf clean all

COPY setting.log run-cyrus.sh /usr/local/bin/
COPY letsencrypt /etc/letsencrypt
RUN chmod -R 444 /etc/letsencrypt

#/etc/imapd.conf
RUN sed -i -e "/sasl_pwcheck_method/ s/:.*/: auxprop/" \
	-e "/virtdomains/ s/:.*/: userid/" \
	-e "/tls_server_cert/ s/:.*/: \/etc\/letsencrypt\/live\/$SSL_DOMAIN\/fullchain.pem/" \
	-e "/tls_server_key/ s/:.*/: \/etc\/letsencrypt\/live\/$SSL_DOMAIN\/privkey.pem/" \
	-e "/tls_client_ca_file/ s/:.*/: \/etc\/letsencrypt\/live\/$SSL_DOMAIN\/chain.pem/" \
	-e "/tls_client_ca_dir/ s/:.*/: \/etc\/letsencrypt\/live\/$SSL_DOMAIN\//" \
	-e "/configdirectory/ s/:.*/: \/data/" \
	-e "/partition-default/ s/:.*/: \/spool/" \
	-e "\$a sasl_sasldb_path: /conf/sasldb2" \
	-e "\$a servername: $SSL_DOMAIN" \
	-e "\$a serverinfo: off" \
	-e "\$a syslog_facility: LOCAL6" \
	-e "\$a autocreate_post: yes" \
	-e "\$a autocreate_quota_messages: 0" \
	-e "\$a autocreate_quota: 0" \
	-e "\$a defaultdomain: $SSL_DOMAIN" \
	-e "\$a sync_authname: cyrus@mail_pod" \
	-e "\$a sync_password: $replpassword" \
	-e "\$a sync_compress: true" \
	-e "\$a sync_log: true" \
	-e "\$a sync_repeat_interval: 60" \
	-e "\$a sync_host: $replSSL_DOMAIN" \
	-e "\$a shutdown_file: /run/cyrus/sync/shutdown" /etc/imapd.conf

#/etc/cyrus.conf
RUN sed -i -e "/^#.*idled/ s/#//" \
	-e "/recover/ s/\$/\n  sync         cmd=\"sync_client -r \"/" \
	-e "/^#.*lmtp/ s/lmtpd/lmtpd -a/" \
	-e "/^#.*lmtp/ s/\"lmtp\"/\"localhost:lmtp\" proto=\"tcp\"/" \
	-e "/^#.*lmtp/ s/#//" /etc/cyrus.conf

#/etc/rsyslog.conf
RUN sed -i -e "/imjournal/ s/^/#/" \
	-e "s/off/on/" \
	-e "s/var\/log/log/g" /etc/rsyslog.conf && \
	echo "local6.*        /log/imapd.log" >> /etc/rsyslog.d/cyrus.conf && \
	echo "auth.debug      /log/auth.log" >> /etc/rsyslog.d/cyrus.conf 

RUN  chmod 755 /usr/local/bin/run-cyrus.sh
ENTRYPOINT ["/usr/local/bin/run-cyrus.sh"]
