version: '3.7'
services:
  mail_img:
    build: .
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt
      - /home/docker_home:/home
      #- /etc/opendkim/:/etc/opendkim/
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/docker_log/:/var/log/
    image: mail
    container_name: mail
