FROM centos
MAINTAINER kusari-k

ARG SSL_DOMAIN 
ARG USER_DOMAIN
ARG password="cyruspassword"
ENV Cpass $password

RUN sed -i -e "\$a fastestmirror=true" /etc/dnf/dnf.conf
RUN dnf update -y && \
	dnf install -y rsyslog cyrus-imapd cyrus-sasl cyrus-sasl-plain && \
	dnf clean all

COPY setting.log run-cyrus-replica.sh /usr/local/bin/
COPY letsencrypt /etc/letsencrypt

#/etc/imapd.conf
RUN sed -i -e "/sasl_pwcheck_method/ s/:.*/: auxprop/" \
	-e "/virtdomains/ s/:.*/: userid/" \
	-e "/tls_server_cert/ s/:.*/: \/etc\/letsencrypt\/live\/$SSL_DOMAIN\/fullchain.pem/" \
	-e "/tls_server_key/ s/:.*/: \/etc\/letsencrypt\/live\/$SSL_DOMAIN\/privkey.pem/" \
	-e "/tls_client_ca_file/ s/:.*/: \/etc\/letsencrypt\/live\/$SSL_DOMAIN\/chain.pem/" \
	-e "/tls_client_ca_dir/ s/:.*/: \/etc\/letsencrypt\/live\/$SSL_DOMAIN\//" \
	-e "\$a syslog_facility: LOCAL6" \
	-e "\$a autocreate_post: yes" \
	-e "\$a autocreate_quota_messages: 0" \
	-e "\$a autocreate_quota: 0" \
	-e "\$a defaultdomain: localhost" /etc/imapd.conf

#/etc/cyrus.conf
RUN sed -i -e "/^#.*idled/ s/#//" \
	-e "/^#.*lmtp/ s/\"lmtp\"/\"localhost:lmtp\" proto=\"tcp\"/" \
	-e "/^#.*lmtp/ s/#//" /etc/cyrus.conf

#user setting
RUN echo $password|saslpasswd2 -c -p -u mail_pod cyrus

RUN grep "^user:" /usr/local/bin/setting.log | \
	sed "s/^user://" | \
	awk -F '[:@]' '{print $1,$2,$3}' | \
	sed -ze "s/\n/ /g" | \ 
	xargs -n 3 -d " " bash -c 'echo $2|saslpasswd2 -c -p -u $1 $0'

#authority setting
RUN mkdir -p -m 750 /var/lib/cyrus /var/spool/cyrus  && \
	chown -R cyrus:mail /var/lib/cyrus /var/spool/cyrus && \
	chmod 777 /etc/sasldb2 && \
	chmod -R 777 /etc/letsencrypt

#/etc/rsyslog.conf
RUN sed -i -e "/imjournal/ s/^/#/" \
	-e "s/off/on/" /etc/rsyslog.conf && \
	echo "local6.*        /var/log/imapd.log" >> /etc/rsyslog.d/cyrus.conf && \
	echo "auth.debug      /var/log/auth.log" >> /etc/rsyslog.d/cyrus.conf

RUN  chmod 755 /usr/local/bin/run-cyrus-replica.sh
ENTRYPOINT ["/usr/local/bin/run-cyrus-replica.sh"]
