version: '3.7'
services:
  mail:        
    build: .
    image: mail
    container_name: mail
    restart: always
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - /home/docker_home/mail/:/home
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/docker_log/mail:/var/log/
networks:
  default:
    external:
      name: default_bridge
