FROM centos:8
MAINTAINER kusari-k

ARG SSL_DOMAIN 
ARG MAIL_DOMAIN

RUN sed -i -e "\$a fastestmirror=true" /etc/dnf/dnf.conf
RUN dnf update -y && \
	dnf install -y rsyslog postfix cyrus-sasl cyrus-sasl-plain && \
	dnf clean all

COPY setting.log run-postfix.sh /usr/local/bin/
COPY letsencrypt /etc/letsencrypt
RUN touch /usr/local/bin/slave

#/etc/postfix/main.cf
RUN postconf \
	"inet_interfaces=all" \
	"mydestination=localhost" \
	"myhostname=slave.localhost" \
	"mydomain=localhost" \
	"smtpd_tls_cert_file=/etc/letsencrypt/live/$SSL_DOMAIN/fullchain.pem" \
	"smtpd_tls_key_file=/etc/letsencrypt/live/$SSL_DOMAIN/privkey.pem" \
	"smtpd_recipient_restrictions=permit_mynetworks permit_sasl_authenticated reject_unauth_destination" \
	"smtpd_sasl_auth_enable = yes" \
	"alias_database = hash:/conf/aliases" \
	"alias_maps = hash:/conf/aliases" \
	"relay_domains = $MAIL_DOMAIN" \
	"transport_maps = hash:/conf/transport" \
	"inet_protocols =ipv4" \
	"smtpd_banner = ESMTP" \
	"queue_directory = /spool" \
	"smtpd_tls_loglevel = 1"

#/etc/postfix/master.cf
RUN sed -i -e "/^#submission/ s/^#//" /etc/postfix/master.cf
RUN postconf -P \
	"submission/inet/syslog_name=postfix/submission" \
	"submission/inet/syslog_name=postfix/submission" \
	"submission/inet/smtpd_tls_security_level=encrypt" \
	"submission/inet/smtpd_sasl_auth_enable=yes" \
	"submission/inet/smtpd_tls_auth_only=yes" \
	"submission/inet/smtpd_reject_unlisted_recipient=no" \
	"submission/inet/smtpd_recipient_restrictions=" \
	"submission/inet/smtpd_relay_restrictions=permit_sasl_authenticated,reject"

#/etc/sasl2/smtpd.conf
RUN sed -i -e "s/saslauthd/auxprop/" \
	-e "2i sasldb_path: /conf/sasldb2" /etc/sasl2/smtpd.conf 

#/etc/rsyslog.conf
RUN sed -i -e "/imjournal/ s/^/#/" \
	-e "s/off/on/" \
	-e "s/var\/log/log/g" /etc/rsyslog.conf

RUN  chmod 755 /usr/local/bin/run-postfix.sh
ENTRYPOINT ["/usr/local/bin/run-postfix.sh"]
