FROM centos:8
MAINTAINER kusari-k

ARG SSL_DOMAIN 
ARG MAIL_DOMAIN

RUN sed -i -e "\$a fastestmirror=true" /etc/dnf/dnf.conf
RUN dnf update -y && \
	dnf install -y rsyslog postfix cyrus-sasl cyrus-sasl-plain && \
	dnf clean all

COPY setting.log run-postfix.sh /usr/local/bin/
COPY letsencrypt /etc/letsencrypt
RUN touch /usr/local/bin/master

#/etc/postfix/main.cf
RUN postconf -e "inet_interfaces = all" && \
	postconf -e "mydestination = localhost" && \
	postconf -e "myhostname = master.localhost" && \
	postconf -e "mydomain = localhost" && \
	postconf -e "smtpd_tls_cert_file = /etc/letsencrypt/live/$SSL_DOMAIN/fullchain.pem" && \
	postconf -e "smtpd_tls_key_file = /etc/letsencrypt/live/$SSL_DOMAIN/privkey.pem" && \
	postconf -e "smtpd_recipient_restrictions = permit_mynetworks permit_sasl_authenticated reject_unauth_destination" && \
	postconf -e "smtpd_sasl_auth_enable = yes" && \
	postconf -e "alias_database = hash:/conf/aliases" && \
	postconf -e "alias_maps = hash:/conf/aliases" && \
	postconf -e "virtual_transport = lmtp:inet:localhost" && \
	postconf -e "virtual_mailbox_domains = $MAIL_DOMAIN" && \
	postconf -e "virtual_mailbox_maps = hash:/conf/vmailbox" && \
	postconf -e "inet_protocols = ipv4" && \
	postconf -e "smtpd_banner = ESMTP" && \
	postconf -e "queue_directory = /spool" && \
	postconf -e "smtpd_tls_loglevel = 1"

#/etc/postfix/master.cf
RUN sed -i -e "/^#submission/ s/^#//" /etc/postfix/master.cf && \
	postconf -P "submission/inet/syslog_name=postfix/submission" && \
	postconf -P "submission/inet/smtpd_tls_security_level=encrypt" && \
	postconf -P "submission/inet/smtpd_sasl_auth_enable=yes" && \
	postconf -P "submission/inet/smtpd_tls_auth_only=yes" && \
	postconf -P "submission/inet/smtpd_reject_unlisted_recipient=no" && \
	postconf -P "submission/inet/smtpd_recipient_restrictions=" && \
	postconf -P "submission/inet/smtpd_relay_restrictions=permit_sasl_authenticated,reject"

#/etc/sasl2/smtpd.conf
RUN sed -i -e "s/saslauthd/auxprop/" \
	-e "2i sasldb_path: /conf/sasldb2" /etc/sasl2/smtpd.conf 

#/etc/rsyslog.conf
RUN sed -i -e "/imjournal/ s/^/#/" \
	-e "s/off/on/" \
	-e "s/var\/log/log/g" /etc/rsyslog.conf

RUN  chmod 755 /usr/local/bin/run-postfix.sh
ENTRYPOINT ["/usr/local/bin/run-postfix.sh"]
