version: '3.7'

services:
  MAIL:
    build:
      context: .
      args:
        main_FQDN: example.com
        main_DOMAIN: example.com
    image: test_mail
    container_name: test_MAIL
    restart: always
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/docker_home/mail/localhost:/home
      - /var/log/docker_log/mail:/var/log

networks:
  default:
    external:
      name: default_bridge
