version: '2'
services:
  mail_img:
    build: .
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - /mnt:/mnt
      - /etc/opendkim/keys/server_name:/etc/opendkim/keys/server_name
      - /etc/letsencrypt:/etc/letsencrypt:ro
    image: mail
    container_name: mail

